name: Build and print a greeting

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  my-job:
    name: execute
    runs-on: sdwan01-2gb-fsn1-2
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
